name: nf
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0=cpu_0
  - _tflow_select=2.3.0=mkl
  - abseil-cpp=20200225.1=h4a8c4bd_2
  - absl-py=0.9.0=py36_0
  - appnope=0.1.0=py36hf537a9a_0
  - arrow-cpp=0.16.0=py36h6d334da_2
  - astor=0.8.0=py36_0
  - attrs=19.3.0=py_0
  - aws-sdk-cpp=1.7.164=h6f10caa_0
  - backcall=0.1.0=py36_0
  - basemap=1.2.0=py36h0acbc05_0
  - basemap-data-hires=1.2.0=0
  - blas=1.0=mkl
  - bleach=3.1.0=py36_0
  - bokeh=1.4.0=py36_0
  - boost-cpp=1.72.0=hdf9ef73_0
  - brotli=1.0.7=h4a8c4bd_1001
  - bzip2=1.0.8=h0b31af3_2
  - c-ares=1.15.0=h1de35cc_1001
  - ca-certificates=2019.11.28=hecc5488_0
  - certifi=2019.11.28=py36h9f0ad1d_1
  - curl=7.68.0=h8754def_0
  - cycler=0.10.0=py36hfc81398_0
  - dbus=1.13.12=h90a0687_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - descartes=1.1.0=py_4
  - entrypoints=0.3=py36_0
  - et_xmlfile=1.0.1=py36h1315bdc_0
  - expat=2.2.6=h0a44026_0
  - ezodf=0.3.2=py_2
  - freetype=2.9.1=hb4e5f40_0
  - fribidi=1.0.5=h1de35cc_0
  - gast=0.2.2=py36_0
  - geographiclib=1.50=py_0
  - geopy=1.21.0=py_0
  - geos=3.6.2=h5470d99_2
  - gettext=0.19.8.1=h15daf44_3
  - gflags=2.2.2=h4a8c4bd_1002
  - glib=2.63.1=hd977a24_0
  - glog=0.4.0=h6de7cb9_1
  - google-pasta=0.1.8=py_0
  - graphite2=1.3.13=h2098e52_0
  - graphviz=2.42.3=h98dfb87_0
  - grpc-cpp=1.27.3=h21656f1_1
  - grpcio=1.16.1=py36h044775b_1
  - h5py=2.10.0=py36h3134771_0
  - hdf5=1.10.4=hfa1e0ec_0
  - icu=64.2=h6de7cb9_1
  - importlib_metadata=1.5.0=py36_0
  - intel-openmp=2019.4=233
  - ipykernel=5.1.4=py36h39e3cac_0
  - ipython=7.12.0=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.5.1=py_0
  - jdcal=1.4.1=py_0
  - jedi=0.16.0=py36_0
  - jinja2=2.11.1=py_0
  - joblib=0.14.1=py_0
  - jpeg=9c=h1de35cc_1001
  - jsonschema=3.2.0=py36_0
  - jupyter=1.0.0=py36_7
  - jupyter_client=5.3.4=py36_0
  - jupyter_console=6.1.0=py_0
  - jupyter_contrib_core=0.3.3=py_2
  - jupyter_contrib_nbextensions=0.5.1=py36_0
  - jupyter_core=4.6.1=py36_0
  - jupyter_highlight_selected_word=0.2.0=py36_1000
  - jupyter_latex_envs=1.4.4=py36_1000
  - jupyter_nbextensions_configurator=0.4.1=py36_0
  - keras=2.3.1=0
  - keras-applications=1.0.8=py_0
  - keras-base=2.3.1=py36_0
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.1.0=py36h0a44026_0
  - krb5=1.16.4=hddcf347_0
  - libcurl=7.68.0=h709d2b2_0
  - libcxx=9.0.1=1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libevent=2.1.10=hafa8578_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=hdd342a3_7
  - libpng=1.6.37=ha441bb4_0
  - libprotobuf=3.11.4=hd9629dc_0
  - libsodium=1.0.16=h3efe00b_0
  - libssh2=1.8.2=hcdc9a53_2
  - libtiff=4.1.0=h2ae36a8_6
  - libwebp-base=1.1.0=h0b31af3_3
  - libxgboost=0.90=h0a44026_1
  - libxml2=2.9.9=hf6e021a_1
  - libxslt=1.1.33=h320ff13_0
  - llvm-openmp=9.0.1=h28b9765_2
  - lml=0.0.9=py_0
  - lxml=3.8.0=py36_0
  - lz4-c=1.8.3=h6de7cb9_1001
  - markdown=3.1.1=py36_0
  - markupsafe=1.1.1=py36h1de35cc_0
  - matplotlib=3.1.3=py36_0
  - matplotlib-base=3.1.3=py36h9aa3819_0
  - missingno=0.4.2=py_1
  - mistune=0.8.4=py36h1de35cc_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py36hfbe908c_0
  - mkl_fft=1.0.15=py36h5e564d8_0
  - mkl_random=1.1.0=py36ha771720_0
  - more-itertools=8.2.0=py_0
  - nb_conda=2.2.1=py36_0
  - nb_conda_kernels=2.2.2=py36_0
  - nbconvert=5.6.1=py36_0
  - nbformat=5.0.4=py_0
  - ncurses=6.2=h0a44026_0
  - notebook=6.0.3=py36_0
  - numpy=1.16.6=py36h81c90fd_0
  - numpy-base=1.16.6=py36h6575580_0
  - olefile=0.46=py36_0
  - openpyxl=3.0.3=py_0
  - openssl=1.1.1e=h0b31af3_0
  - opt_einsum=3.1.0=py_0
  - packaging=20.1=py_0
  - pandas=0.24.1=py36h0a44026_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - parquet-cpp=1.5.1=2
  - parso=0.6.1=py_0
  - patsy=0.5.1=py36_0
  - pcre=8.43=h0a44026_0
  - pexpect=4.8.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pillow=7.0.0=py36h4655f20_0
  - pip=20.0.2=py36_1
  - pixman=0.38.0=h1de35cc_0
  - plotly=4.5.0=py_0
  - pluggy=0.13.1=py36_0
  - proj=6.2.1=hfd5b9e3_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=3.0.3=py_0
  - protobuf=3.11.4=py36h0a44026_0
  - ptyprocess=0.6.0=py36_0
  - py=1.8.1=py_0
  - py-xgboost=0.90=py36h0a44026_1
  - pyarrow=0.16.0=py36h398749e_2
  - pyexcel=0.5.15=py_0
  - pyexcel-io=0.5.20=py_0
  - pygments=2.5.2=py_0
  - pyparsing=2.4.6=py_0
  - pyproj=2.4.1=py36h1526c70_0
  - pyqt=5.9.2=py36h655552a_2
  - pyrsistent=0.15.7=py36h1de35cc_0
  - pyshp=2.1.0=py_0
  - pytest=5.3.5=py36_0
  - pytest-mock=1.13.0=py_1
  - python=3.6.10=h359304d_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - pytz=2019.3=py_0
  - pyyaml=5.3=py36h1de35cc_0
  - pyzmq=18.1.1=py36h0a44026_0
  - qt=5.9.7=h8cf7e54_3
  - qtconsole=4.6.0=py_1
  - re2=2020.03.03=h4a8c4bd_0
  - readline=7.0=h1de35cc_5
  - retrying=1.3.3=py36_2
  - scikit-learn=0.22.1=py36h27c97d8_0
  - scikit-plot=0.3.7=py_1
  - scipy=1.4.1=py36h9fa6033_0
  - seaborn=0.10.0=py_0
  - send2trash=1.5.0=py36_0
  - setuptools=45.2.0=py36_0
  - sip=4.19.8=py36h0a44026_0
  - six=1.14.0=py36_0
  - snappy=1.1.8=h4a8c4bd_1
  - sqlite=3.31.1=ha441bb4_0
  - statsmodels=0.11.0=py36h1de35cc_0
  - tensorboard=2.0.0=pyhb38c66f_1
  - tensorflow=2.0.0=mkl_py36ha38f243_0
  - tensorflow-base=2.0.0=mkl_py36h66b1bf0_0
  - tensorflow-estimator=2.0.0=pyh2649769_0
  - termcolor=1.1.0=py36_1
  - terminado=0.8.3=py36_0
  - testpath=0.4.4=py_0
  - texttable=1.6.2=py_0
  - thrift-cpp=0.13.0=h0a7acf3_2
  - tk=8.6.8=ha441bb4_0
  - tornado=6.0.3=py36h1de35cc_3
  - traitlets=4.3.3=py36_0
  - wcwidth=0.1.8=py_0
  - webencodings=0.5.1=py36_1
  - werkzeug=1.0.0=py_0
  - wheel=0.34.2=py36_0
  - widgetsnbextension=3.5.1=py36_0
  - wrapt=1.11.2=py36h1de35cc_0
  - xlrd=1.2.0=py36_0
  - xz=5.2.4=h1de35cc_4
  - yaml=0.1.7=hc338f04_2
  - zeromq=4.3.1=h0a44026_3
  - zipp=2.2.0=py_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.4.4=hed8d7c8_2
  - pip:
    - branca==0.4.0
    - chardet==3.0.4
    - chart-studio==1.0.0
    - folium==0.10.1
    - idna==2.9
    - requests==2.23.0
    - sklearn==0.0
    - torch==1.4.0
    - urllib3==1.25.8

